package database

import (
	"database/sql"
)

func Migrate(db *sql.DB) error {
	_, err := db.Exec(`
		    CREATE TABLE IF NOT EXISTS USER (
		        ID          INTEGER PRIMARY KEY AUTOINCREMENT,
		        USERNAME    TEXT UNIQUE NOT NULL,
		        PASSWORD    TEXT NOT NULL,
		        CREATE_AT  	DATETIME DEFAULT CURRENT_TIMESTAMP,
		        UPDATED_AT 	DATETIME
		    );

			CREATE TABLE IF NOT EXISTS PROFILE (
				ID			INTEGER PRIMARY KEY AUTOINCREMENT,
				USER_ID		INTEGER NOT NULL,
			    NAME        TEXT NOT NULL,
			    TITLE       TEXT NOT NULL,
			    BIO         TEXT NOT NULL DEFAULT '',
				CREATED_AT	DATETIME DEFAULT CURRENT_TIMESTAMP,
				UPDATED_AT	DATETIME,
				FOREIGN KEY (USER_ID) REFERENCES USER(ID)
			);

		    CREATE TABLE IF NOT EXISTS SOCIAL_MEDIA (
		        ID           INTEGER PRIMARY KEY AUTOINCREMENT,
		        TITLE        TEXT NOT NULL,
		        REDIRECT_URL TEXT NOT NULL,
		        CREATED_AT   DATETIME DEFAULT CURRENT_TIMESTAMP,
		        UPDATED_AT   DATETIME DEFAULT CURRENT_TIMESTAMP
		    );

		    CREATE TABLE IF NOT EXISTS USER_SOCIAL_MEDIA (
		        USER_ID         INTEGER NOT NULL,
		        SOCIAL_MEDIA_ID INTEGER NOT NULL,
		        URL_CLICKS      INTEGER DEFAULT 0,
		        POSITION        INTEGER DEFAULT 0,
		        CREATED_AT      DATETIME DEFAULT CURRENT_TIMESTAMP,
		        PRIMARY KEY (USER_ID, SOCIAL_MEDIA_ID),
		        FOREIGN KEY (USER_ID) REFERENCES USER(ID),
		        FOREIGN KEY (SOCIAL_MEDIA_ID) REFERENCES SOCIAL_MEDIA(ID)
		    );

			CREATE TABLE IF NOT EXISTS ROLE (
				ID				INTEGER PRIMARY KEY AUTOINCREMENT,
				ROLE_NAME		TEXT NOT NULL,
				DESCRIPTION		TEXT NOT NULL,
				DELETED			INTEGER DEFAULT 0,
				CREATED_AT		DATETIME DEFAULT CURRENT_TIMESTAMP,
				UPDATED_AT 		DATETIME
			);

			CREATE TABLE IF NOT EXISTS PERMISSION (
				ID					INTEGER PRIMARY KEY AUTOINCREMENT,
				PERMISSION_NAME		TEXT NOT NULL,
				DESCRIPTION			TEXT NOT NULL,
				CREATED_AT			DATETIME DEFAULT CURRENT_TIMESTAMP,
				UPDATED_AT			DATETIME
			);

			CREATE TABLE IF NOT EXISTS ROLE_PERMISSION (
				ROLE_ID				INTEGER NOT NULL,
				PERMISSION_ID		INTEGER NOT NULL,
				CREATED_AT			DATETIME DEFAULT CURRENT_TIMESTAMP,
				UPDATED_AT			DATETIME,
				PRIMARY KEY (ROLE_ID, PERMISSION_ID),
				FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID),
				FOREIGN KEY (PERMISSION_ID) REFERENCES PERMISSION(ID)
			);

			CREATE TABLE IF NOT EXISTS USER_ROLE (
				USER_ID			INTEGER NOT NULL,
				ROLE_ID			INTEGER NOT NULL,
				CREATED_AT 		DATETIME DEFAULT CURRENT_TIMESTAMP,
				UPDATED_AT 		DATETIME,
				PRIMARY KEY (USER_ID, ROLE_ID),
				FOREIGN KEY (USER_ID) REFERENCES USER(ID),
				FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID)
			);
		`)

	return err
}
