package database

import (
	"database/sql"
)

func Migrate(db *sql.DB) error {
	_, err := db.Exec(`
		    CREATE TABLE IF NOT EXISTS USER (
		        ID          INTEGER PRIMARY KEY AUTOINCREMENT,
		        USERNAME    TEXT UNIQUE NOT NULL,
		        PASSWORD    TEXT NOT NULL,
		        NAME        TEXT NOT NULL,
		        TITLE       TEXT NOT NULL,
		        BIO         TEXT NOT NULL DEFAULT '',
		        CREATE_AT  	DATETIME DEFAULT CURRENT_TIMESTAMP,
		        UPDATED_AT 	DATETIME DEFAULT CURRENT_TIMESTAMP
		    );

		    CREATE TABLE IF NOT EXISTS SOCIAL_MEDIA (
		        ID           INTEGER PRIMARY KEY AUTOINCREMENT,
		        TITLE        TEXT NOT NULL,
		        REDIRECT_URL TEXT NOT NULL,
		        CREATED_AT   DATETIME DEFAULT CURRENT_TIMESTAMP,
		        UPDATED_AT   DATETIME DEFAULT CURRENT_TIMESTAMP
		    );

		    CREATE TABLE IF NOT EXISTS USER_SOCIAL_MEDIA (
		        USER_ID         INTEGER NOT NULL,
		        SOCIAL_MEDIA_ID INTEGER NOT NULL,
		        URL_CLICKS      INTEGER DEFAULT 0,
		        POSITION        INTEGER DEFAULT 0,
		        CREATED_AT      DATETIME DEFAULT CURRENT_TIMESTAMP,
		        PRIMARY KEY (USER_ID, SOCIAL_MEDIA_ID),
		        FOREIGN KEY (USER_ID) REFERENCES USER(ID) ON DELETE CASCADE,
		        FOREIGN KEY (SOCIAL_MEDIA_ID) REFERENCES SOCIAL_MEDIA(ID) ON DELETE CASCADE
		    );
		`)

	return err
}
